config/routes.rb
Rails.application.routes.draw do

  namespace :api do
      get 'posts' => 'posts#index'
      post 'posts' => 'posts#create'
      get 'rooms/:id' => 'rooms#show'
      post 'rooms' => 'rooms#create'
    end

  root 'sessions#new'
  post '/' => 'sessions#create'
  get 'signout' => 'sessions#delete', as: :signout
  get 'users/new' => 'users#new', as: :register
  post 'users' => 'users#create', as: :users
  get 'users/:id' => 'users#show', as: :user

  get 'rooms/index' => 'rooms#index', as: :rooms
  get 'rooms/find' => 'rooms#find', as: :find_rooms
  get 'rooms/:id' => 'rooms#show', as: :room
  post 'rooms/index' => 'rooms#create'

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  belongs_to :room

  validates :text, presence: true

  def timestamp
    created_at.strftime '%l:%M %p'
  end

end

app/models/room.rb
class Room < ActiveRecord::Base

  has_many :users
  has_many :posts

  validates :room_name, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts

  has_secure_password

  validates :user_name, :password, :first_name, :last_name, presence: true
  validates :user_name, :email, uniqueness: true
  attachment :photo

end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController

  skip_before_filter :verify_authenticity_token

  before_filter :default_request_format

  def default_request_format
  request.format = :json
  end
  
  before_action do
    if @current_user.nil?
      # redirect_to sign_in_path
      render json: {authenticated: false}, status: 401
    end
  end

  def index
     @posts = Post.order("created_at desc")
  end

  def create
    @post = Post.new params.require(:post).permit(:text)
    @post.user = @current_user
    @post.room = Room.find_by(params[:id])
     if @post.save
      render :show
    else
      render json: {errors: @post.errors}, status: 422
    end
  end
end

app/controllers/api/rooms_controller.rb
class Api::RoomsController < ApplicationController

  skip_before_filter :verify_authenticity_token
  before_filter :default_request_format

def default_request_format
  request.format = :json
end

  before_action do
    if @current_user.nil?
      # redirect_to sign_in_path
      render json: {authenticated: false}, status: 401
    end
  end

  def show
     @room = Room.find_by id: params[:id]
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_action do
  @current_user = User.find_by id: session[:user_id]
end

def authenticate_user!
  if @current_user.blank?
    redirect_to signin_path
  end
end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

   before_action do
     @current_user = User.find_by id: session[:user_id]
     if @current_user.blank?
       redirect_to login_path
     end
   end

   def find
     @rooms=Room.all
     @room = Room.find_by id: params[:id]

   end

   def index
     @rooms = Room.all
     @room = Room.new
   end

   def show
     @room = Room.find_by id: params[:id]
     @rooms = Room.all.order("created_at desc")

   end


   def new
     @room = Room.new
   end

   def create
     @room = Room.new params.require(:room).permit(:room_name)

     if @room.save
       redirect_to room_path(id: @room.id)
     else
       render :new
       flash.now[:alert] = "Add a Room Name Please"
     end
   end

   def delete
   end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:email]
  password = params[:password]

  user = User.find_by email: email
  if user && user.authenticate(password)
    session[:user_id] = user.id
    redirect_to rooms_path
  else
    render :new
  end
end

  def delete
    session[:user_id] = nil
  redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user=User.new
  end

  def create
    @user = User.new params.require(:user).permit(:user_name, :password, :photo, :first_name, :last_name, :email)
    if @user.save
   @user.save
     session[:user_id] = @user.id
     redirect_to rooms_path
   else
     render :new
   end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slack: Be Less Busy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:300' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/rooms/find.html.erb
  <span class='find-container'>
<%=image_tag 'logo.png', class:'findlogoimg' %>
  <span class="find-logo-welcome">
    slack
  </span>
</span>
<center><div class="find-welcome">
<p style="font-size:70px;">Hey <%=@current_user.first_name%>!</p>
<p style="font-size:50px;">These are all the existing teams you can join.</p>
</div>
<div class="room-list">
<% @rooms.each do |f|%>
<p class="room-item"><%= link_to f.room_name, room_path(id: f.id), class:'room-list-links'%></p>
<%end%>
</div></center>

app/views/rooms/index.html.erb
<div class="welcome-content">
  <div class="add-rooms">
    <span class="logospan">
      <span>
        <%=image_tag 'logo.png', class:'slacklogo' %>
        <span class="logo-welcome">
          slack
        </span>
      </span>
      <div class="new-team-container">
        Looking to join an existing team?
        <%=link_to find_rooms_path do%>
        <div class="room-index-link">
          Find a Team
        </div><%end%>
      </div>
    </span>
    <div class="add-room-question">
      <p>
        Hey
        <%=@current_user.first_name %>!
        <p>What do you want to</p>
        <p>call your Slack Team?</p>
      </div>
      <div class="suggestion">
        <p>
          <center>Name your team after the group
          </center>
        </p>
        <p>
          <center>that will be using Slack togethor.<center></p>
          </div>
          <% if @room.errors.any? %>
          <%= pluralize(@room.errors.count, 'error') %>
          need your attention.
          <ul>
            <% @room.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
          <% end %>
          <center style="padding-top:20px;">
            <%= form_for @room do |f| %>
            <%= f.text_field :room_name, class:"newroom", placeholder:'Ex. Thermo Study Group' %>
            <%= f.submit 'Go', class:'new-room-submit' %>
            <%end %>

          </center>
        </div>
        <%= image_tag 'art.png', class:'art'%>
      </div>

app/views/rooms/show.html.erb
<div class="room_container">
  <div class="sidebar-container">

    <p class="side-container">
      <%= link_to rooms_path do %>
      <span>
        <i class="fa fa-slack fa-2x" aria-hidden="true"></i>
        <span class="logo">
          slack
        </span>
      </span>
      <%end%>
      <%= link_to signout_path do %>
      <i class="fa fa-sign-out fa-2x" aria-hidden="true"></i>
      <%end %>

    </p>
    <%= @current_user.first_name %>
    <%= @current_user.last_name %>

    <p class="channels">
      <p>TEAMS (<%= @rooms.length %>)</p>
    </p>

    <% @rooms.each do |room| %>
    <p class="room-name">#<%= link_to room.room_name, room_path(id: room.id), class:"rooms-list" %></p>
    <% end %>

  </div>

  <div class="messaging">
    <div class="room_title">
      #<%= @room.room_name%>
    </div>
    <%= react_component 'Posts' %>
    <%= react_component 'Form' %>
  </div>

</div>

app/views/users/new.html.erb
<div class="welcome-container">

  <div class="logo-container2">
    <i class="fa fa-slack fa-2x" aria-hidden="true"></i>
    <span class="logo">
      slack
    </span>
  </div>
<div class="content-container">
<div class="signupform">
<% if @user.errors.any? %>
      <%= pluralize(@user.errors.count, 'error') %> need your attention.
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
    <center>
<%= form_for @user do |f| %>
<%= f.text_field :first_name, placeholder:"First Name", class:"signupfield" %>
<%= f.text_field :last_name, placeholder:"Last Name", class:"signupfield" %>
<%= f.text_field :user_name, placeholder:"User Name", class:"signupfield" %>
<%= f.text_field :email, placeholder:"Email", class:"signupfield" %>
<%= f.password_field :password, placeholder:"Password", class:"signupfield" %>
<%= f.attachment_field :photo, class:'browse'%>
<%= f.submit "Sign Up", class:"signinsubmit" %>
<%end%>
<p class="signupline">
  Already have an account?
  <%= link_to "Sign In", root_path, class:"signuplink" %>
</p>
</center>
</div>
</div>
</div>

app/views/welcome/index.html.erb
<%= link_to "Sign in", signin_path %>
<%= link_to "Join", register_path %>